version: "3.8"

services:
  tree:
    image: tree:latest
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - tree_network

networks:
  tree_network:
    driver: overlay
